// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Valesor Development
//
// Emits src/css/_tokens.generated.css from the JSON token source. This is the
// ONLY generated CSS; everything else in src/css is hand-written and @imports it.
// Both color schemes are emitted twice on purpose:
//   - via prefers-color-scheme, so a plain page follows the OS (the real world), and
//   - via [data-scheme='light'|'dark'], so the demo can force both at once (regressions).
// Forced attributes are declared AFTER the media block and use higher specificity,
// so an explicit choice always wins over the OS default.

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { loadRawTokens, semanticColors, accentColors, SCHEMES, IMPRINTS } from './lib/tokens.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'css', '_tokens.generated.css');

const tree = loadRawTokens();

// ---- small serializers --------------------------------------------------------

const needsQuote = (name) => !/^[a-zA-Z-][a-zA-Z0-9-]*$/.test(name);
const fontStack = (arr) => arr.map((n) => (needsQuote(n) ? `'${n}'` : n)).join(', ');
const decl = (name, value) => `  --${name}: ${value};`;

function block(selector, decls) {
  return `${selector} {\n${decls.join('\n')}\n}`;
}

// ---- scale tokens (scheme-independent) ----------------------------------------

// Iterate a token group's real entries, skipping DTCG metadata ($description, etc.).
const tokenEntries = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));

function scaleDecls() {
  const d = [];
  const { font, space, radius, border, shadow, z, breakpoint, measure } = tree;

  d.push(decl('font-sans', fontStack(font.family.sans.$value)));
  d.push(decl('font-mono', fontStack(font.family.mono.$value)));
  for (const [k, n] of tokenEntries(font.weight)) d.push(decl(`font-weight-${k}`, n.$value));
  for (const [k, n] of tokenEntries(font.size)) d.push(decl(`font-size-${k}`, n.$value));
  for (const [k, n] of tokenEntries(font.leading)) d.push(decl(`leading-${k}`, n.$value));
  for (const [k, n] of tokenEntries(font.tracking)) d.push(decl(`tracking-${k}`, n.$value));
  d.push(decl('measure', measure.$value));

  for (const [k, n] of tokenEntries(space)) d.push(decl(`space-${k}`, n.$value));
  for (const [k, n] of tokenEntries(radius)) d.push(decl(`radius-${k}`, n.$value));
  for (const [k, n] of tokenEntries(border.width)) d.push(decl(`border-width-${k}`, n.$value));
  for (const [k, n] of tokenEntries(shadow)) d.push(decl(`shadow-${k}`, n.$value));
  for (const [k, n] of tokenEntries(z)) d.push(decl(`z-${k}`, n.$value));
  for (const [k, n] of tokenEntries(breakpoint)) d.push(decl(`breakpoint-${k}`, n.$value));

  return d;
}

// ---- semantic colors (per scheme) ---------------------------------------------

function semanticDecls(scheme) {
  return Object.entries(semanticColors(tree, scheme)).map(([role, hex]) =>
    decl(`color-${role}`, hex),
  );
}

// ---- accent colors (per imprint, per scheme) ----------------------------------

function accentDecls(imprint, scheme) {
  return Object.entries(accentColors(tree, imprint, scheme)).map(([role, hex]) =>
    decl(`color-${role}`, hex),
  );
}

// ---- assemble -----------------------------------------------------------------

const parts = [];
parts.push(`/* GENERATED by tools/build-tokens.mjs from tokens/*.json — do not edit by hand. */`);

// Scale + light semantics as the base :root (also the forced-light selector).
parts.push(block(":root,\n[data-scheme='light']", [...scaleDecls(), ...semanticDecls('light')]));

// Dark semantics via OS preference.
parts.push(
  `@media (prefers-color-scheme: dark) {\n${block(
    '  :root',
    semanticDecls('dark').map((l) => '  ' + l),
  ).replace(/\n/g, '\n')}\n}`,
);

// Dark semantics forced (wins over the media default by source order).
parts.push(block("[data-scheme='dark']", semanticDecls('dark')));

// Per-imprint accents: base (light) → OS-dark → forced-dark → forced-light.
for (const imprint of IMPRINTS) {
  const cls = `.imprint-${imprint}`;
  parts.push(block(cls, accentDecls(imprint, 'light')));
  parts.push(
    `@media (prefers-color-scheme: dark) {\n${block(
      '  ' + cls,
      accentDecls(imprint, 'dark').map((l) => '  ' + l),
    )}\n}`,
  );
  parts.push(
    block(`[data-scheme='dark'] ${cls},\n${cls}[data-scheme='dark']`, accentDecls(imprint, 'dark')),
  );
  parts.push(
    block(
      `[data-scheme='light'] ${cls},\n${cls}[data-scheme='light']`,
      accentDecls(imprint, 'light'),
    ),
  );
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, parts.join('\n\n') + '\n');

// eslint-disable-next-line no-console
console.log(`build-tokens: wrote ${OUT} (${SCHEMES.length} schemes, ${IMPRINTS.length} imprints)`);
